# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
      displayName: 'Use Python 3.9'

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '.'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
        replaceExistingArchive: true
      displayName: 'Archive files'

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - script: |
        source venv/bin/activate
        pytest
      displayName: 'Run tests'

- stage: Deploy
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Free Trial(4e8b4bd0-7eee-426c-afeb-50d1ceb34677)'
        appType: 'webAppLinux'
        appName: 'pythonapp76282'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      displayName: 'Deploy to Azure Web App'