# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master  # Adjust this to your default branch name, e.g., 'master' or 'main'
 
pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  # Specify the Python version you want
    addToPath: true
 
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
 
- script: |
    python -m unittest discover -s test -p "test_endpoints.py"
  displayName: 'Run tests'
 
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'MyAzureServiceConnection'  # The name of your Azure service connection
#     appName: 'webappusecase5'  # Name of your Azure Web App
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'  # Path to your deployment package
#     deploymentMethod: 'zipDeploy'
#   displayName: 'Deploy to Azure Web App'

# - stage: Deploy
#   dependsOn: Test
#   jobs:
#   - job: DeployJob
#     steps:
#     - task: AzureWebApp@1
#       inputs:
#         azureSubscription: 'Free Trial(4e8b4bd0-7eee-426c-afeb-50d1ceb34677)'
#         appType: 'webAppLinux'
#         appName: 'pythonapp76282'
#         package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#       displayName: 'Deploy to Azure Web App'